import { APPLICATION_ROLES, type ApplicationRole } from "@/types/auth";
import { type Permission, PERMISSIONS } from "@/types/permissions";

export const ALL_PERMISSIONS = Object.values(
  PERMISSIONS,
) satisfies Permission[];

export const ROLE_PERMISSIONS: Record<ApplicationRole, readonly Permission[]> =
  {
    [APPLICATION_ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,
    [APPLICATION_ROLES.MANAGER]: [
      PERMISSIONS.DASHBOARD_VIEW,
      PERMISSIONS.ANALYTICS_VIEW,
      PERMISSIONS.ORGANIZATIONS_VIEW,
      PERMISSIONS.ORGANIZATIONS_MANAGE,
      PERMISSIONS.USERS_VIEW,
      PERMISSIONS.USERS_INVITE,
      PERMISSIONS.USERS_EDIT,
      PERMISSIONS.SUBSCRIPTIONS_VIEW,
      PERMISSIONS.NOTIFICATIONS_VIEW,
      PERMISSIONS.NOTIFICATIONS_MANAGE,
      PERMISSIONS.AUDIT_LOG_VIEW,
      PERMISSIONS.SETTINGS_PROFILE_VIEW,
      PERMISSIONS.SETTINGS_PROFILE_EDIT,
      PERMISSIONS.SETTINGS_ORGANIZATION_VIEW,
      PERMISSIONS.SETTINGS_ORGANIZATION_EDIT,
      PERMISSIONS.SETTINGS_APPEARANCE_VIEW,
      PERMISSIONS.SETTINGS_APPEARANCE_EDIT,
    ],
    [APPLICATION_ROLES.MEMBER]: [
      PERMISSIONS.DASHBOARD_VIEW,
      PERMISSIONS.NOTIFICATIONS_VIEW,
      PERMISSIONS.SETTINGS_PROFILE_VIEW,
      PERMISSIONS.SETTINGS_PROFILE_EDIT,
      PERMISSIONS.SETTINGS_APPEARANCE_VIEW,
      PERMISSIONS.SETTINGS_APPEARANCE_EDIT,
    ],
  };

export const PERMISSION_SUMMARIES: Partial<Record<Permission, string>> = {
  [PERMISSIONS.DASHBOARD_VIEW]: "Dashboard",
  [PERMISSIONS.ANALYTICS_VIEW]: "Analytics",
  [PERMISSIONS.ORGANIZATIONS_VIEW]: "Organizations",
  [PERMISSIONS.ORGANIZATIONS_MANAGE]: "Organization management",
  [PERMISSIONS.USERS_VIEW]: "Users",
  [PERMISSIONS.USERS_INVITE]: "Invite users",
  [PERMISSIONS.USERS_EDIT]: "Edit users",
  [PERMISSIONS.USERS_SUSPEND]: "Suspend users",
  [PERMISSIONS.USERS_DELETE]: "Delete users",
  [PERMISSIONS.ROLES_VIEW]: "Roles",
  [PERMISSIONS.ROLES_MANAGE]: "Manage roles",
  [PERMISSIONS.SUBSCRIPTIONS_VIEW]: "Subscriptions",
  [PERMISSIONS.SUBSCRIPTIONS_MANAGE]: "Manage subscriptions",
  [PERMISSIONS.BILLING_VIEW]: "Billing",
  [PERMISSIONS.BILLING_MANAGE]: "Manage billing",
  [PERMISSIONS.INVOICES_VIEW]: "Invoices",
  [PERMISSIONS.NOTIFICATIONS_VIEW]: "Notifications",
  [PERMISSIONS.NOTIFICATIONS_MANAGE]: "Manage notifications",
  [PERMISSIONS.AUDIT_LOG_VIEW]: "Audit log",
  [PERMISSIONS.SETTINGS_PROFILE_VIEW]: "View profile",
  [PERMISSIONS.SETTINGS_PROFILE_EDIT]: "Edit profile",
  [PERMISSIONS.SETTINGS_ORGANIZATION_VIEW]: "Organization settings",
  [PERMISSIONS.SETTINGS_ORGANIZATION_EDIT]: "Edit organization settings",
  [PERMISSIONS.SETTINGS_SECURITY_VIEW]: "Security settings",
  [PERMISSIONS.SETTINGS_SECURITY_MANAGE]: "Manage security settings",
  [PERMISSIONS.SETTINGS_BILLING_VIEW]: "Billing settings",
  [PERMISSIONS.SETTINGS_BILLING_MANAGE]: "Manage billing settings",
  [PERMISSIONS.SETTINGS_APPEARANCE_VIEW]: "Appearance settings",
  [PERMISSIONS.SETTINGS_APPEARANCE_EDIT]: "Edit appearance settings",
};
