export const PERMISSIONS = {
  DASHBOARD_VIEW: "dashboard.view",
  ANALYTICS_VIEW: "analytics.view",
  ORGANIZATIONS_VIEW: "organizations.view",
  ORGANIZATIONS_MANAGE: "organizations.manage",
  USERS_VIEW: "users.view",
  USERS_INVITE: "users.invite",
  USERS_EDIT: "users.edit",
  USERS_SUSPEND: "users.suspend",
  USERS_DELETE: "users.delete",
  ROLES_VIEW: "roles.view",
  ROLES_MANAGE: "roles.manage",
  SUBSCRIPTIONS_VIEW: "subscriptions.view",
  SUBSCRIPTIONS_MANAGE: "subscriptions.manage",
  BILLING_VIEW: "billing.view",
  BILLING_MANAGE: "billing.manage",
  INVOICES_VIEW: "invoices.view",
  NOTIFICATIONS_VIEW: "notifications.view",
  NOTIFICATIONS_MANAGE: "notifications.manage",
  AUDIT_LOG_VIEW: "audit_log.view",
  SETTINGS_PROFILE_VIEW: "settings.profile.view",
  SETTINGS_PROFILE_EDIT: "settings.profile.edit",
  SETTINGS_ORGANIZATION_VIEW: "settings.organization.view",
  SETTINGS_ORGANIZATION_EDIT: "settings.organization.edit",
  SETTINGS_SECURITY_VIEW: "settings.security.view",
  SETTINGS_SECURITY_MANAGE: "settings.security.manage",
  SETTINGS_BILLING_VIEW: "settings.billing.view",
  SETTINGS_BILLING_MANAGE: "settings.billing.manage",
  SETTINGS_APPEARANCE_VIEW: "settings.appearance.view",
  SETTINGS_APPEARANCE_EDIT: "settings.appearance.edit",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
